version: '3.8'

# ================================================================
#                       СЕРВИСЫ
# ================================================================
services:
  # ----------------------------------------------------------------
  # СЕРВИС №1: "АНАЛИЗАТОР"
  # ----------------------------------------------------------------
  ticket-analyzer:
    # "Собери, этот сервис из Dockerfile-а в текущей папке"
    build: .
    container_name: ticket-analyzer

    # --- Секция №1: "ПОРЯДОК, БЛ***!" (ЗАВИСИМОСТИ) ---
    # ЗАПУСКАЙСЯ ТОЛЬКО ПОСЛЕ ТОГО, КАК МОНГО НЕ ПРОСТО ЗАПУСТИТСЯ,
    # А СТАНЕТ "ЗДОРОВОЙ" (пройдет свой healthcheck).
    depends_on:
      mongo:
        condition: service_healthy

    # --- Секция №2: "НАСТРОЙКИ (КОНФИГУРАЦИЯ) ---
    # Прокидываем адрес Монго ВНУТРЬ контейнера.
    # Spring Boot подхватит эту переменную и перекроет то, что в application.yml.
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/ticket_database

    # --- Секция №3: "КОМАНДА НА ВЫПОЛНЕНИЕ (ЗАПУСК) ---
    # Эта команда целиком передается как АРГУМЕНТЫ в твой ENTRYPOINT (wait-for-it.sh)
    # 
    # Аргумент №1 для скрипта -> 'mongo:27017' (кого, ждать)
    # Аргумент №2 для скрипта -> '--' (разделитель)
    # Аргументы №3 и далее -> 'java -jar app.jar "arg1" "arg2"' (ЧТО, запустить ПОСЛЕ)
    command: >
      mongo:27017 
      -- 
      java -jar app.jar "Владивосток" "Тель-Авив"

  # ----------------------------------------------------------------
  # СЕРВИС №2: "СКЛАД ДАННЫХ" (НАША, MONGODB)
  # ----------------------------------------------------------------
  mongo:
    image: mongo:6.0
    container_name: ticket_mongo_db
    
    # Перезапускать, если упала, пока мы ее сами не остановим. Надежность!
    restart: unless-stopped
    
    ports:
      # Прокидываем порт, чтобы ты мог подключиться к базе со своего компа через Compass.
      - "27017:27017"

    volumes:
      # Именованный volume, чтобы данные, НЕ ТЕРЯЛИСЬ между перезапусками.
      - mongo-data:/data/db

    # --- САМАЯ ВАЖНАЯ, СЕКЦИЯ ДЛЯ ЗАВИСИМОСТЕЙ ---
    # "ПРОВЕРКА ПУЛЬСА" БАЗЫ ДАННЫХ
    healthcheck:
      # Команда, которую Docker будет запускать внутри контейнера, чтобы проверить, жива ли Монга
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s   # Проверять каждые 10 секунд
      timeout: 5s     # Считать проверку проваленной, если она длится дольше 5 секунд
      retries: 5      # Сделать 5 попыток, прежде чем пометить сервис как "unhealthy"

# ================================================================
#             ХРАНИЛИЩА, (VOLUMES)
# ================================================================
volumes:
  # Декларируем наш именованный volume
  mongo-data:
    driver: local