package ru.abriel.ticket_analyzer.domain.model.ticket;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import java.time.Instant;
import java.util.List;

/**
 * Represents the document structure for storing a batch of tickets in MongoDB.
 * This acts as a wrapper that includes metadata like the upload timestamp.
 *
 * @param id The unique identifier of the document, generated by MongoDB.
 * @param uploadedAt The timestamp indicating when this batch of tickets was saved.
 * @param tickets The actual list of {@link Ticket} domain models.
 */
@Document(collection = "ticket_batches")
public record TicketDocument(@Id String id, Instant uploadedAt, List<Ticket> tickets) {}
